# exifutils configuration
# Only settings that differ from defaults need to be specified here.

exifTool {
  # Path to the exiftool executable
  path = ""
}

dateTime {
  # Default time zone for guessing date and time of creation if only local date is available.
  # Format: IANA Time Zone Database (TZDB) identifier, such as America/New_York
  # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  # If not set, system default time zone is used.
  #timeZone = ""
}
