# exifutils configuration
# Only settings that differ from defaults need to be specified here.

exifTool {
  # Path to the exiftool executable
  # Leave empty to use exiftool from PATH
  path = ""
}

# Uncomment to override default time zone:
# dateTime.timeZone = "Europe/Bratislava"

# Uncomment to override rename pattern:
# rename.pattern = "IMG_${date,yyyyMMdd}_${date,HHmmss}"
