# Default configuration for exifutils
# These values are used if not overridden in user's application.conf

exifTool {
  # Path to the exiftool executable (empty means use PATH)
  path = ""
}

rename {
  # Pattern for new file name, where following variables are available (extension is preserved):
  # ${prefix}: IMG for images, VID for video files
  # ${date}: pattern for formatting date of creation
  #          specs: https://docs.oracle.com/en/java/javase/21/docs/api/java.base/java/time/format/DateTimeFormatter.html
  pattern = "IMG_${date,yyyyMMdd}_${date,HHmmss}"
}
